export const Actions = {
  DISABLE_SUBMIT_BUTTON: 'DISABLE_SUBMIT_BUTTON',
  ON_VALID_ALL: 'ON_VALID_ALL',
  ON_CHANGE_FIELD: 'ON_CHANGE_FIELD',
  ERRORS: 'ERRORS',
  SUCCESS: 'SUCCESS',
  FIELD_VALUES: 'FIELD_VALUES',
  ALL_FIELDS: 'ALL_FIELDS'
};